#!/bin/bash
qrencode -o address.png 'MECARD:N:Botka,Vladimir;URL:https://www.botka.info;EMAIL:vbotka@gmail.com;NOTE: PGP ID: 2048R/8ED44F01, Fingerprint: 6DA4 E1B9 8290 81B6 E60E B564 90D1 9912 8ED4 4F01;'
